# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quote.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquote.proto\x12\x05quote\" \n\x0cQuoteRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\".\n\rQuoteResponse\x12\r\n\x05quote\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t2E\n\x0cQuoteService\x12\x35\n\x08GetQuote\x12\x13.quote.QuoteRequest\x1a\x14.quote.QuoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUOTEREQUEST']._serialized_start=22
  _globals['_QUOTEREQUEST']._serialized_end=54
  _globals['_QUOTERESPONSE']._serialized_start=56
  _globals['_QUOTERESPONSE']._serialized_end=102
  _globals['_QUOTESERVICE']._serialized_start=104
  _globals['_QUOTESERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
