# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quote_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quote_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12quote_stream.proto\x12\x05quote\" \n\x0cQuoteRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\".\n\rQuoteResponse\x12\r\n\x05quote\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t2\x89\x01\n\rQuoteStreamer\x12;\n\x0cStreamQuotes\x12\x13.quote.QuoteRequest\x1a\x14.quote.QuoteResponse0\x01\x12;\n\nChatQuotes\x12\x13.quote.QuoteRequest\x1a\x14.quote.QuoteResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quote_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUOTEREQUEST']._serialized_start=29
  _globals['_QUOTEREQUEST']._serialized_end=61
  _globals['_QUOTERESPONSE']._serialized_start=63
  _globals['_QUOTERESPONSE']._serialized_end=109
  _globals['_QUOTESTREAMER']._serialized_start=112
  _globals['_QUOTESTREAMER']._serialized_end=249
# @@protoc_insertion_point(module_scope)
