# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import quote_stream_pb2 as quote__stream__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in quote_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuoteStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamQuotes = channel.unary_stream(
                '/quote.QuoteStreamer/StreamQuotes',
                request_serializer=quote__stream__pb2.QuoteRequest.SerializeToString,
                response_deserializer=quote__stream__pb2.QuoteResponse.FromString,
                _registered_method=True)
        self.ChatQuotes = channel.stream_stream(
                '/quote.QuoteStreamer/ChatQuotes',
                request_serializer=quote__stream__pb2.QuoteRequest.SerializeToString,
                response_deserializer=quote__stream__pb2.QuoteResponse.FromString,
                _registered_method=True)


class QuoteStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamQuotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatQuotes(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuoteStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamQuotes': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamQuotes,
                    request_deserializer=quote__stream__pb2.QuoteRequest.FromString,
                    response_serializer=quote__stream__pb2.QuoteResponse.SerializeToString,
            ),
            'ChatQuotes': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatQuotes,
                    request_deserializer=quote__stream__pb2.QuoteRequest.FromString,
                    response_serializer=quote__stream__pb2.QuoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quote.QuoteStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quote.QuoteStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuoteStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamQuotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/quote.QuoteStreamer/StreamQuotes',
            quote__stream__pb2.QuoteRequest.SerializeToString,
            quote__stream__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatQuotes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/quote.QuoteStreamer/ChatQuotes',
            quote__stream__pb2.QuoteRequest.SerializeToString,
            quote__stream__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
